#! /bin/sh

# ] ---- AUTOSTART ---- [

nitrogen --restore &
betterlockscreen -u /home/tarun/Pictures/arcolinux/wallpaper.jpg &
--no-startup-id xfce4-power-manager &
xinput set-prop 12 309 1 &
--no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
blueman-applet &
#setxkbmap pl &
flameshot &
picom -b &
nm-applet &
sh ~/.config/polybar/launch.sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width         2
bspc config window_gap           8

bspc config normal_border_color "#2A2426"
bspc config focused_border_color "#2196F3"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Spotify desktop='^5' follow=on
bspc rule -a lutis desktop='^4' follow=on





